---
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script: nosetests
cache: pip
deploy:
  provider: lambda
  function_name: "lambda-test"
  role: "arn:aws:iam::609459096019:role/service-role/radradradScraper"
  handler_name: "lambdatest.lambda_handler"
  access_key_id: ""
  secret_access_key: ""
